### ISSUE TITLE
KO on radxa Fogwise® AirBox

### ISSUE THREAD

**Issue by tourshomer** [zifeng-radxa/flux.1_tpu#1]
following the setup, 
i get the following error : 

xxxx@Airbox:~/flux.1_tpu$ python3 flux_pipeline.py --models schnell
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
argv: ['flux_pipeline.py', '--models', 'schnell']
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./models/clip_combined.bmodel]. Thanks for your patience...
[BMODEL][ModelCtx:350] FATAL: File[./models/clip_combined.bmodel] is broken ..

**Comment by tourshomer** [comment]
will you publish a docker image ???  https://hub.docker.com/u/radxazifeng278

**Comment by ZIFENG278** [comment]
Could you provide more error details? like how much of your TPU memory settings,

**Comment by ZIFENG278** [comment]
> will you publish a docker image ??? https://hub.docker.com/u/radxazifeng278

not sure, if more people ask, i may publish one

**Comment by tourshomer** [comment]
> Could you provide more error details? like how much of your TPU memory settings,

not sure how to that (could you point me out the error log file )  .. but i did follow the prerequiste , 
(.venv) linaro@Airbox:~/flux.1_tpu$ memory_edit.sh -c -npu **7615** -vpu **2360** -vpp **2360**  bm1684x_sm7m_v1.0.dtb
followed by the sync & reboot


```
(.venv) linaro@Airbox:~/flux.1_tpu$ memory_edit.sh -p bm1684x_sm7m_v1.0.dtb

 Info: use dts file /opt/sophon/memory_edit/output/bm1684x_sm7m_v1.0.dts
Info: chip is bm1684x
Info: =======================================================================
Info: get ddr information ...
Info: ddr12_size 8589934592 Byte [8192 MiB]
Info: ddr3_size 4294967296 Byte [4096 MiB]
Info: ddr4_size 4294967296 Byte [4096 MiB]
Info: ddr_size 16384 MiB
Info: =======================================================================
Info: get max memory size ...
Info: max npu size: 0x1dbf00000 [7615 MiB]
Info: max vpu size: 0xb8000000 [2944 MiB]
Info: max vpp size: 0x100000000 [4096 MiB]
Info: =======================================================================
Info: get now memory size ...
Info: now npu size: 0x1dbf00000 [7615 MiB]
Info: now vpu size: 0x93800000 [2360 MiB]
Info: now vpp size: 0x93800000 [2360 MiB]
(.venv) linaro@Airbox:~/flux.1_tpu$

```

models seems to be there

(.venv) linaro@Airbox:~/flux.1_tpu$ ls -rlt models/
total 4648
drwxrwxr-x 2 linaro linaro    4096 Dec  7 10:16 assets
-rw-rw-r-- 1 linaro linaro    2278 Dec  7 10:16 README.md
-rw-rw-r-- 1 linaro linaro     135 Dec  7 10:16 dev_w4bf16_transform_combined.bmodel
-rw-rw-r-- 1 linaro linaro     134 Dec  7 10:16 clip_combined.bmodel
-rw-rw-r-- 1 linaro linaro     135 Dec  7 10:16 t5_combined.bmodel
-rw-rw-r-- 1 linaro linaro     135 Dec  7 10:16 schnell_w4bf16_transform_combined.bmodel
-rw-rw-r-- 1 linaro linaro 4719772 Dec  7 10:16 ids_emb.pt
drwxrwxr-x 2 linaro linaro    4096 Dec  7 10:16 tokenizer
drwxrwxr-x 2 linaro linaro    4096 Dec  7 10:16 tokenizer_2
-rw-rw-r-- 1 linaro linaro     132 Dec  7 10:16 vae_decoder_F16.bmodel




when using gradio  the error happen when i load model (wether schnell or dev)
when lauching  using cli  .. i got the same message

**Comment by tourshomer** [comment]
> > will you publish a docker image ??? https://hub.docker.com/u/radxazifeng278
> 
> not sure, if more people ask, i may publish one
OK !

i try 
to promote fogwise airbox for local LLM  ( [discord](https://discord.com/channels/862602258452578314/1227084481488355409/1310285348332371979) )

and 

to learn more on compiler TPU MLIR   ( [doc TPU MLIR](https://en.sophgo.com/curriculum/description.html?category_id=9) )  but  i can not read chinese doc/training nor download it for translation 

anyway thank you [ZIFENG278](https://github.com/ZIFENG278)  on all effort you put to make it easier for newcomer

**Comment by ZIFENG278** [comment]
There have English docs reference of TPU-MLIR, https://tpumlir.org/en/docs/quick_start/index.html

**Comment by ZIFENG278** [comment]
> [BMODEL][ModelCtx:350] FATAL: File[./models/clip_combined.bmodel] is broken ..

Another reason to make model load failed is the model file is broken, you can use command 
```bash
bmrt_test --bmodel YOUR_BMODEL_FILE_PATH
```
to test all the bmodel file is correct, particular `clip_combined.bmodel`, if all the bmodel can success load and run, means all models is correct,

by the way, you can use `bm-smi` to dynamic check TPU memory usage status, make sure TPU memory is enough

**Comment by tourshomer** [comment]
> > [BMODEL][ModelCtx:350] FATAL: File[./models/clip_combined.bmodel] is broken ..
> 
> Another reason to make model load failed is the model file is broken, you can use command
> 
> ```shell
> bmrt_test --bmodel YOUR_BMODEL_FILE_PATH
> ```
> 
> to test all the bmodel file is correct, particular `clip_combined.bmodel`, if all the bmodel can success load and run, means all models is correct,
> 
> by the way, you can use `bm-smi` to dynamic check TPU memory usage status, make sure TPU memory is enough



Thank you ZIFENG278 , it realy helped

indeed the models were not totally  downloaded , and the space was full.


After i downloaded  `clip_combined.bmodel` from  [https://www.modelscope.cn/models/tpu-mlir/FLUX.1_TPU/files](https://modelscope-cn.translate.goog/models/tpu-mlir/FLUX.1_TPU/files)

i performed a test on bmrt_test --bmodel  ./models/clip_combined.bmodel
this time it was ok

For  now i have to download the other model (<20Go) so i'll need to add a disk... i'll keep you informed

**Comment by tourshomer** [comment]
i copied all the models and files on a card , mounted it under ./models ==> it's working

really impressed to run locally FLUX1 on an all in one hardware that cost me less than 350$

- schnell  take less than 2 minutes to generate an image
- dev   take around 7/8 minutes to generate an image


again thank you for the support [ZIFENG278](https://github.com/ZIFENG278)

**Comment by ZIFENG278** [comment]
yeah, i think you can not find another device which can run FLUX.1 in 2 mins and cheaper than Fogwise Airbox for now.
hope you enjoy
